/* 2017-11-10 */
-- 创建数据库
CREATE DATABASE asl_ums_temp;

-- 创建部门表
CREATE TABLE al_department (
	id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "id",
	code VARCHAR(255) COMMENT "编码",
	name VARCHAR(255) COMMENT "名称",
	description TEXT COMMENT "描述",
	createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
	updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间"
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* 2017-11-14 */
-- 创建权限表
CREATE TABLE al_jurisdiction (
	id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "id",
	name VARCHAR(255) COMMENT "名称",
	description TEXT COMMENT "描述",
	createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
	updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间"
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* 2017-11-15 */
-- 创建角色表
CREATE TABLE al_role (
	id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "id",
	name VARCHAR(255) COMMENT "名称",
	description TEXT COMMENT "描述",
	createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
	updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间"
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 创建角色权限表
CREATE TABLE al_role_jurisdiction (
	role_id BIGINT(20) NOT NULL COMMENT "角色id",
	jurisdiction_id BIGINT(20) NOT NULL COMMENT "权限id",
	CONSTRAINT fk_role_jurisdiction_id FOREIGN KEY (role_id) REFERENCES al_role (id),
	CONSTRAINT fk_jurisdiction_role_id FOREIGN KEY (jurisdiction_id) REFERENCES al_jurisdiction (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;