/* 2017-11-10 */
-- 创建部门表
CREATE TABLE al_department (
	id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "id",
	code VARCHAR(255) COMMENT "编码",
	name VARCHAR(255) COMMENT "名称",
	description TEXT COMMENT "描述",
	createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
	updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间"
)ENGINE=InnoDB DEFAULT CHARSET=utf8;